### ISSUE TITLE
.join method could be simpler?

### ISSUE THREAD

**Issue by m4v15** [ZooeyMiller/mc-array-methods-reduce#1]
Maybe you did it on purpose, but with `.join` you can use the fact that `.reduce` will use the first element of the array ass the accumulator and start at index 1 if no second argument (i.e. initial value) is provided. So the solution could be like this:
```js
function join(array, string) {
  //your code here
  return array.reduce(function(acc, el) {
    return acc + string + el
  })
}
```

However you might have done it your way to introduce the extra `index, arr` arguments in the `.reduce` method. In which case ignore me 🙃 

---
Edit: I just saw I accidentally type 'ass' instead of 'as' but leaving it for the lols

**Comment by stevehopkinson** [comment]
Big thumbs up to this! :+1:

**Comment by shiryz** [comment]
btw, this is exactly the example used in MSDN :arrow_down: , so perhaps it's good to keep Zooey's version.

```js
// Define the callback function.  
function appendCurrent (previousValue, currentValue) {  
    return previousValue + "::" + currentValue;  
    }  

// Create an array.  
var elements = ["abc", "def", 123, 456];  

// Call the reduce method, which calls the callback function  
// for each array element.  
var result = elements.reduce(appendCurrent);  

document.write(result);  

// Output:  
//  abc::def::123::456  
```
